# Backend
backend = "glx";
vsync = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;

# Shadows
shadow = true;
shadow-radius = 8;
shadow-opacity = 0.4;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-exclude = [
    "class_g = 'i3bar'",
    "class_g = 'i3-frame'",
    "_GTK_FRAME_EXTENTS@:c",
    "class_g = 'slop'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

# Fading
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;

# Opacity
inactive-opacity = 0.95;
frame-opacity = 0.9;

# Rounded corners
corner-radius = 6;
rounded-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];
